version: '2'
services:
  boleto-api:
    build: 
      context: ..
      dockerfile: ./devops/Dockerfile      
    volumes:
      - c:/boleto_json_store/:/home/mundipagg/upMongo
      - c:/cert_boleto_api/:/home/mundipagg/boleto_cert/
    ports:
      - "3000:3000"
    network_mode: bridge

    
        