version: 2
jobs:
  build:
    docker:
      - image: golang:1.8
    
    working_directory: /go/src/github.com/mundipagg/boleto-api

    steps:
      - checkout
      - run:
          name: Get dependencies
          command: go get -t -d -v ./...
      - run: 
          name: Building
          command: go build -v
      - run: 
          name: Move artifacts
          command: mv boleto-api devops/
      - run: 
          name: Testing
          command: go test $(go list ./... | grep -v /vendor/) -v
      - persist_to_workspace:
          root: .
          paths:
            - devops/
  publish:
    working_directory: /app/devops
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: /app
      - deploy:
          name: Push application Docker image
          command: |
            ls -la
            docker build -t ${DOCKER_ACCOUNT}/${PROJECT_NAME} .
            docker tag ${DOCKER_ACCOUNT}/${PROJECT_NAME} "${DOCKER_ACCOUNT}/${PROJECT_NAME}:${CIRCLE_BRANCH}"
            docker tag ${DOCKER_ACCOUNT}/${PROJECT_NAME} "${DOCKER_ACCOUNT}/${PROJECT_NAME}:${CIRCLE_SHA1:0:8}"
            docker login ${DOCKER_ACCOUNT} -u ${DOCKER_USER} -p ${DOCKER_PASS}
            docker push "${DOCKER_ACCOUNT}/${PROJECT_NAME}"
  deploy:
    machine: true
    steps:
      - run:
          name: Send deployment webhook to Rancher
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              curl -X POST \
                ${RANCHER_PROD_DEPLOY_URL} \
                -H 'Content-Type: application/json' \
                -d '{
                        "push_data": {
                        "tag": "master"
                        },
                        "repository": {
                        "repo_name": "${DOCKER_ACCOUNT}/${PROJECT_NAME}"
                        }
              }'
            fi
            if [ "${CIRCLE_BRANCH}" == "develop" ]; then
              curl -X POST \
                ${RANCHER_STG_DEPLOY_URL} \
                -H 'Content-Type: application/json' \
                -d '{
                        "push_data": {
                        "tag": "develop"
                        },
                        "repository": {
                        "repo_name": "${DOCKER_ACCOUNT}/${PROJECT_NAME}"
                        }
              }'
            fi

workflows:
  version: 2
  build_publish_deploy:
    jobs:
      - build
      - publish:
          requires:
            - build
          filters:
            branches:
              only: 
                - master
                - develop
      - hold:
          type: approval
          requires:
            - publish
          filters:
            branches:
              only: 
                - master
                - develop
      - deploy:
          requires:
            - hold
